name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      POSTGRESQL_VER: f5eda17f89d160d0a89ac7c5db4636bdaefd48e6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
      - name: Log in to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_CONTAINER }}
      - name: Push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: swoole/Dockerfile
          build-args: |
            CN=0
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}